services:
  - type: web
    name: kotonoha-48o0
    runtime: docker
    plan: free
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: kotonoha-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: kotonoha-db
    databaseName: kotonoha_production
    user: kotonoha_user
    plan: free
